CC = gcc
AR = ar

SRC_DIR = src
BUILD_DIR = build
LIBS = -lSDL2
INCLUDES =
ARGS = -Wall -std=c2x -g -O0 -D_DEBUG $(LIBS) $(INCLUDES)

##### MODULES ######
# ENGINE MODULE
ENGINE_SRC_DIR = $(SRC_DIR)/engine
ENGINE_BUILD_DIR = $(BUILD_DIR)/engine
ENGINE_OUTPUT_DIR = $(ENGINE_BUILD_DIR)/export
ENGINE_OUTPUT_LIB_DIR = $(ENGINE_OUTPUT_DIR)/lib
ENGINE_OUTPUT_INC_DIR = $(ENGINE_OUTPUT_DIR)/include
ENGINE_OUTPUT_LIB_NAME = libengine.a
ENGINE_OUTPUT_LIB = $(ENGINE_OUTPUT_LIB_DIR)/$(ENGINE_OUTPUT_LIB_NAME)
ENGINE_OBJS = engine/engine.o
ENGINE_OBJS_PATH = $(ENGINE_BUILD_DIR)/engine.o
ENGINE_INCLUDES =
ENGINE_LIBS =
ENGINE_ARGS = $(ARGS) $(MAIN_LIBS) $(MAIN_INCLUDES)

# MAIN MODULE
MAIN_SRC_DIR = $(SRC_DIR)/main
MAIN_BUILD_DIR = $(BUILD_DIR)/main
MAIN_OUTPUT_DIR = $(MAIN_BUILD_DIR)/bin
MAIN_OUTPUT_APP_NAME = sdl.app
MAIN_OUTPUT_APP = $(MAIN_OUTPUT_DIR)/$(MAIN_OUTPUT_APP_NAME)
MAIN_OBJS = main/main.o
MAIN_OBJS_PATH = $(MAIN_BUILD_DIR)/main.o
MAIN_INCLUDES = -I$(ENGINE_OUTPUT_INC_DIR)
MAIN_LIBS = -L$(ENGINE_OUTPUT_LIB_DIR) -lengine
MAIN_ARGS = $(ARGS) $(MAIN_LIBS) $(MAIN_INCLUDES)

#####FILES#####
# MAIN FILES
main/main.o:
	$(CC) -c $(MAIN_SRC_DIR)/main.c -o $(MAIN_BUILD_DIR)/main.o $(MAIN_ARGS)
# ENGINE FILES
engine/engine.o:
	$(CC) -c $(ENGINE_SRC_DIR)/engine.c -o $(ENGINE_BUILD_DIR)/engine.o $(ENGINE_ARGS)

#####GENERAL#####
engine: $(ENGINE_OBJS)
	$(AR) rcs $(ENGINE_OUTPUT_LIB) $(ENGINE_OBJS_PATH)
	cp -u $(ENGINE_SRC_DIR)/*.h $(ENGINE_OUTPUT_INC_DIR)

main: engine $(MAIN_OBJS)
	$(CC) $(MAIN_OBJS_PATH) -o $(MAIN_OUTPUT_APP) $(MAIN_ARGS)

all: engine main;

run: all
	./$(MAIN_OUTPUT_APP)
